//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chc.servicemanagertray.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("chc.servicemanagertray.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are free to do whatever you want with this software.
        ///Special thanks to famfamfam.com for the icons.
        /// </summary>
        internal static string About_Text {
            get {
                return ResourceManager.GetString("About_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Manager Tray by ChildhoodCoder.com.
        /// </summary>
        internal static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Manager Tray.
        /// </summary>
        internal static string NotifyIcon_Baloon_Header {
            get {
                return ResourceManager.GetString("NotifyIcon_Baloon_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click this icon to show the application window..
        /// </summary>
        internal static string NotifyIcon_Baloon_Hide {
            get {
                return ResourceManager.GetString("NotifyIcon_Baloon_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} service is {1}..
        /// </summary>
        internal static string NotifyIcon_Baloon_Service_State {
            get {
                return ResourceManager.GetString("NotifyIcon_Baloon_Service_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Manager started.
        /// </summary>
        internal static string NotifyIcon_Baloon_Start {
            get {
                return ResourceManager.GetString("NotifyIcon_Baloon_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite services:.
        /// </summary>
        internal static string NotifyIcon_Menu_FavoriteServicesLabel_Text {
            get {
                return ResourceManager.GetString("NotifyIcon_Menu_FavoriteServicesLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the menu item to toggle the service state..
        /// </summary>
        internal static string NotifyIcon_Menu_FavoriteServicesLabel_Tooltip {
            get {
                return ResourceManager.GetString("NotifyIcon_Menu_FavoriteServicesLabel_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        internal static string NotifyIcon_Menu_Service {
            get {
                return ResourceManager.GetString("NotifyIcon_Menu_Service", resourceCulture);
            }
        }
    }
}
